
// This file has been generated by the GUI designer. Do not modify.
namespace ForcedCleanAddin
{
	public partial class ForcedCleanSettingWidget
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label1;

		private global::Gtk.CheckButton autoCleanCheckButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ForcedCleanAddin.ForcedCleanSettingWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "ForcedCleanAddin.ForcedCleanSettingWidget";
			// Container child ForcedCleanAddin.ForcedCleanSettingWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Forced Clean Addin Setting");
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.autoCleanCheckButton = new global::Gtk.CheckButton();
			this.autoCleanCheckButton.CanFocus = true;
			this.autoCleanCheckButton.Name = "autoCleanCheckButton";
			this.autoCleanCheckButton.Label = global::Mono.Unix.Catalog.GetString("Auto ForcedClean(Run ForcedClean before build)");
			this.autoCleanCheckButton.DrawIndicator = true;
			this.autoCleanCheckButton.UseUnderline = true;
			this.vbox1.Add(this.autoCleanCheckButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.autoCleanCheckButton]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
